### ISSUE TITLE
Bitte keine commits ohne PR

### ISSUE THREAD

**Issue by oqq** [ChemnitzHackt/broetchen#6]
Ich habe gerade gesehen, dass hier neuer Code für den ServiceService gelandet ist, ohne das es einen Pull Request dafür gab.

Können wir uns bitte darauf einigen, dass es immer einen PR geben muss und der auch von einer anderen Partei "gereviewed" wird?

@Manjack21 @ericschw 

Vielleicht ist es auch möglich den master in der GitHub config zu sperren? @ronnyhartenstein

**Comment by ronnyhartenstein** [comment]
Ich könnte mir vorstellen, dass sowas die Motivation zum weiten Mitmachen drückt. Ihr arbeitet doch an der API eh nur zu zweit, muss es da so viel Prozess sein? YOLO im Master sorgt auf jeden Fall für Drive, oder?

**Comment by ronnyhartenstein** [comment]
Wenn @Manjack21 und @ericschw das aber auch befürworten, schau ich dass ich direkte Master-Pushs deaktiviere.

**Comment by oqq** [comment]
Naja, da ist vor zwei Tagen Code gelandet, der so nicht funktionieren kann. Das wäre mir bei einem Review vielleicht aufgefallen und ich hätte darauf eingehen können.

Für den einen ist es vielleicht frustrierend, wenn er seinen Code nicht gleich rein bekommt. Für mich ist es aber frustrierend wenn jeder einfach pushen kann.

Wir können das aber gern Demokratisch lösen. Ich würde mich dann einfach fügen wenn @Manjack21 und @ericschw das anders sehen. :)

**Comment by Manjack21** [comment]
Ich kann mit einem PR-unterstützten Prozess gut leben und ziehe meine Commits jetzt über mein Repo.

**Comment by ronnyhartenstein** [comment]
![image](https://user-images.githubusercontent.com/2638472/32408690-0293d66e-c19d-11e7-99ea-a9fea0f6bdac.png)
Done :)
